import pandas as pd
import re


def format_number(x):
    return f"{x:,.2f}" if pd.notnull(x) else ""

def clean_table(html):
    """Remove the outer <table> tag generated by pandas."""
    html = re.sub(r"<table[^>]*>", "", html)
    html = html.replace("</table>", "")
    return html

def lines(df, theme="light"):
    df_copy = df.copy()

    # Format numeric columns ONLY for display
    for col in df_copy.select_dtypes(include=['float64', 'int64']).columns:
        df_copy[col] = df_copy[col].apply(format_number)

    ten_first = df_copy.head(10)
    ten_last = df_copy.tail(10)

    first_html_raw = ten_first.to_html(index=False, border=0)
    last_html_raw = ten_last.to_html(index=False, border=0)

    first_html = clean_table(first_html_raw)
    last_html = clean_table(last_html_raw)

    first_lines_html = f"""
    <h2>First lines data</h2>
    <div class="table-container">
        <table class="table-custom">
            {first_html}
        </table>
    </div>
    """

    last_lines_html = f"""
    <h2>Last lines data</h2>
    <div class="table-container">
        <table class="table-custom">
            {last_html}
        </table>
    </div>
    """

    return first_lines_html + last_lines_html